name: Remote update execution
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_ID }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PASS }}
        script: |
            whoami
